"""Given: A DNA string s of length at most 1000 nt.

Return: Four integers (separated by spaces) counting the respective number of times that the symbols 'A', 'C', 'G', and 'T' occur in s."""


s="TGGACTACGGAGAACCATGCGATTTATTATCGTTCGGAGCTACATCCACACATGGCGGGCCCGATACGTCGCGACTGAGCTCGTGCTCCTTATAATCAGCCACGAGTCAATACGCTATTGGGCGGTATAAGCCTTCATCCGGAACGTGAAGACTTCAAGATGCGCCTCGAGGGGGTGTCAGGCGTGGATCTTCTCTCGGTGCAAACTTTGTTGGGCTCTGAAGATCTGTGAAGGCAAATATGGCTGGTAAGGAAGTTGTGGCTGACTAGCTACTGCTGTTGATAGGCTATCCACCCCGTCACCATTCGCAGTTCGTTCTTGATCAGTGAGTGCGTATGATTAGGTTTGGGGCGCTCGTTGAAATTGTCCTTAACTGCAACCCTCTAGTTTTGGCTCCGTATAACAACAACTTGTATTGCCAGCGTCGTAATTCAGGTTCCACGGATCCGAACCTGTTACCGGTTCCCTCTTTATAAACGAAATACATAAAGATGCGTGAGTGAGGCCAAGTCTCTTCTCTACATGCATATAGTCCGCTGTCACCCGTGGTATTCATTGGGGAGGCCCTGGACACGGTGAGGAGGTTCAACCTAACACTATGTGTTCAGACGGCCGGCGGCGCCGAGAAGGGTTAAGAGGGAATCGTTCTTCGCTAAAGCCGCGAGCAGCCATAAACAAGGGCCCCGTGCTGAATCCGGTGCGCCTGTCGACAGCCATCACTCGCTCAGGCTTGCTTGACCTCATAACCAGTTAGAGAGGTGCCGCTCTTTGTTGAATTTGAATAGTGGAACACTTATCTCCATGAATATATGTTCGTCCCCCGGCGGGTCCGAGGTACCTCGTCGCCTGGCACCCACTTAGGCCAAGATGCTCGTAACCTAATATCGGAGAGTAATACCATGCACCCATCTTCTACGAA"
a,t,c,g=0,0,0,0

for each in s:
    match each:
        case "A":
            a+=1
        case "T":
            t+=1
        case "C":
            c+=1 
        case "G":
            g+=1

print(f'{a} {c} {g} {t}')

##another attempt

# A=s.count("A")
# G=s.count("G")
# T=s.count("T")
# C=s.count("C")
# print(A,C,G,T)