"""The reverse complement of a DNA string s is the string sc formed by reversing the symbols of s, then taking the complement of each symbol (e.g., the reverse complement of "GTCA" is "TGAC").

Given: A DNA string s of length at most 1000 bp.

Return: The reverse complement sc of s."""

s="GTTTGTCCCGCGAAGCTGGTATCAGCTGCGAGCCTCATTGCGCACCGTGATCAGCACTACAAAGCATGATGACTTCTCGATCCTGCGCTTAGCAGATGCGCTACTAAGCGCTCTGGACAACGCATTCTTTCCGAATATTCTTGCAGGCAAACTACTCCGCTCTTATGAAGAAGAGCTCGCATAAATTATCGTCCTGTGTTGCGTTGTCGCGTGCTCAGACGTGCTCGGGTATATTGCAGGCATTTCTATTCACTTCTAAGCTGTATTTTTAGGTGATACTAACCATAGTTCAGGATACACTGCCAGTATGATCTGCAAACTCAGCATCACAAAGAAGCGCTGCCGGGCGTCGCAAAGCAATCGGACTTATACCATCTAAGTCGAACGACGCTCGACTGAAGACCCTGTAAGAAATGTGTCGAGCCATATCCCGGGAGCCGATTAGGGAACTCAACGGCGGACCGTCATCCCTGAGGAAAAATCGCAATTCAGTCCCCCTCAAGAGGCATGCTCTAAAAAAAGGACTCGAAATGCCTGGAGACGAGCATGGAACCAAACTCTGCAGATAGATATTGGCTAGTTTAACCTAACACGCGTAGTACCATTTCATAACTAACCTACCTCGCAACATAGACAGCCTGTAGTTAGCCCTAACTAACTATCGTGTATCTCTTGGTGGTACGTTGTGTGACTATGATATGGTTCGTTCCGTACGAAATCTACAAGGAGAGATTTGAAAGCACCACTATCAGGGAGACAGTAAACTCTATTGCCAATGCCTTGCGTATCGCTATTGACATGCTAAAACCCGGATTTTTCGAATAAGCACCAAGAACATTGATAGATTGGGAATTCTGCCCCTTTTTTTTAAAGTCTTGATTGCAGGGCTAAAAAACACATTGCTGTCGCTCTTGGTCACCGCGCCGGGATCT"
u=''
sc=''
for each in s:
    match each:
        case "A":
            u+="T"
        case "T":
            u+="A"
        case "C":
            u+="G" 
        case "G":
            u+="C"

for i in range(len(s)-1,-1,-1):
        sc+=u[i]

print(sc)